# Generated by Django 6.0.7 on 2026-08-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_sale_delivered_at_sale_shipped_at_sale_tracking_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('pending_decision', 'Pending seller decision'), ('awaiting_payment', 'Awaiting payment'), ('paid', 'Paid'), ('defaulted', 'Buyer defaulted')], default='awaiting_payment', max_length=20),
        ),
    ]
