# Generated by Django 6.0.7 on 2026-08-17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_kyc_submission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[
                    ('item_not_as_described', 'Item not as described'),
                    ('item_not_received', 'Item not received'),
                    ('payment_issue', 'Payment issue'),
                    ('seller_unresponsive', 'Seller unresponsive'),
                    ('other', 'Other'),
                ], max_length=30)),
                ('description', models.TextField()),
                ('evidence', models.ImageField(blank=True, null=True, upload_to='disputes/evidence/')),
                ('status', models.CharField(choices=[
                    ('open', 'Open'),
                    ('under_review', 'Under review'),
                    ('resolved', 'Resolved'),
                    ('dismissed', 'Dismissed'),
                ], default='open', max_length=20)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_raised', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='auctions.sale')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
